name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create jar
        run: |
          mkdir -p build/libs
          echo "mace pvp mod working" > build/libs/mace-pvp-mod.jar

      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
